stages:
  - test
  - build
  - deploy

variables:
  HOST_IP: $CI_SERVER_HOST
  SSH_USER: root

test:
  image: node:latest
  stage: test
  tags:
    - test
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

build:
  image: node:latest
  stage: build
  tags:
    - build
  before_script:
    - npm install
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - npm run build
    - cd build
    - zip -r ../build.zip .
  artifacts:
    paths:
      - build.zip

deploy:
  stage: deploy
  tags:
    - deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq openssh-client
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no build.zip ${SSH_USER}@${HOST_IP}:~/build.zip
    - ssh -o StrictHostKeyChecking=no ${SSH_USER}@${HOST_IP} "cd /var/www/html/; sudo unzip -o ~/build.zip"